runtime: python39
entrypoint: python main.py

instance_class: F2  # Specifies the instance size (adjust as needed)

# Cloud SQL Configuration
beta_settings:
  cloud_sql_instances: civic-karma-446405-v9:us-central1:voter-db
